# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phpserver', '0003_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
