# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phpserver', '0004_remove_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='github_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
