# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phpserver', '0005_image_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='dockerfile',
            field=models.TextField(),
        ),
    ]
