# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phpserver', '0006_auto_20160330_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='state',
        ),
        migrations.RemoveField(
            model_name='project',
            name='username',
        ),
        migrations.RemoveField(
            model_name='project',
            name='version',
        ),
    ]
